config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts ,only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Remember adding nested routes (schools - reviews : connected)
  resources :schools do 
  	collection do
  		get 'search'
  	end
  	
  	resources :reviews
  end
  root 'schools#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My contact form",
      :to => "nkeshice@myumanitoba.ca",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :school
	belongs_to :user
end

app/models/school.rb
class School < ApplicationRecord
	searchkick
	belongs_to :user
	has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
	has_many :schools
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	before_action :find_school
	before_action :find_review, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]
	
	def new
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.school_id = @school.id
		@review.user_id = current_user.id

		if @review.save
			redirect_to school_path (@school)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @review.update(review_params)
			redirect_to school_path (@school)
		else
			render 'edit'
		end
	end

	def destroy
		@review.destroy
		redirect_to school_path (@school)
	end

	private

		def find_review
			@review = Review.find(params[:id])
		end


		def review_params
			params.require(:review).permit(:rating, :academics, :assistance, :life, :comment, :campus, :return, :delay, :career)
		end

		def find_school
			@school = School.find (params[:school_id])
		end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	before_action :find_school, only: [:show, :edit, :update, :destroy]
	#here we are making sure that the user cannot access certain pages without authentification.
	before_action :authenticate_user!, only: [:new, :edit]

	def search
		if params[:search].present?
			@schools = School.search(params[:search])
		else
			@schools = School.all.order ("created_at DESC")
		end
	end

	def index
		@schools = School.all.order ("created_at DESC")
	end
#to show details of a school
	def show
		if @school.reviews.blank?
			@average_rating = 0
			@average_academics = 0
			@average_assistance = 0
			@average_life = 0
			@average_campus = 0
			@average_return = 0
			@average_delay = 0
			@average_career = 0
		else
			@average_rating = @school.reviews.average(:rating).round(2)
			@average_academics = @school.reviews.average(:academics).round(2)
			@average_assistance = @school.reviews.average(:assistance).round(2)
			@average_life = @school.reviews.average(:life).round(2)
			@average_campus = @school.reviews.average(:campus).round(2)
			@average_return = @school.reviews.average(:return).round(2)
			@average_delay = @school.reviews.average(:delay).round(2)
			@average_career = @school.reviews.average(:career).round(2)
		end
	end

	def new
		@school = current_user.schools.build
	end

	def create
		@school = current_user.schools.build(school_params)

		if @school.save
			redirect_to root_path
		else
			render 'new'
		end

	end

	def update
		if @school.update(school_params)
			redirect_to school_path(@school)
		else
			render 'edit'
		end
	end

	def edit
	end

	def destroy
		@school.destroy
		redirect_to root_path
	end



	private
		def school_params
			params.require(:school).permit(:title, :location, :program)
		end

		def find_school
			@school = School.find (params[:id])
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<h1><center>Hello</center></h1>
<p><center>For a request to add your school or for additional information</center></p>
<p><center>infoschoolreviews@gmail.com</center></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScreenSchools</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-static-top" >
        <ul class="nav navbar-nav topnav">
            <li><%= link_to "Show All", root_path%></li>
        </ul>

        <ul class="nav navbar-nav topnav" id= "myTopnav">

              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              
              <% if user_signed_in? %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Log In", new_user_session_path%></li>
              <% end %>

        </ul>

        <ul class="nav navbar-nav navbar">
              <% if user_signed_in? %> 
                 <!--<li><%= link_to "Add School", new_school_path %></li>-->
              <% end %>
        </ul>

        <ul class="nav navbar-nav navbar">
            <li><%= link_to "Contact Us", new_contact_path %></li>
        </ul>


        <%= form_tag search_schools_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control"%>
          <%= submit_tag "School Search", name: nil, class:"btn btn-custom1"%>
        </p>
        <% end %>
    </nav>

  	<p class="notice"><%= notice %></p>
  	<p class= "alert"><%= alert %></p>

    <div class= "container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@school, @school.reviews.build]) do |f|%>
	<div id= "rating-form">
		<label>Quality</label>
	</div>
	<div id= "rating-academics">
		<label>Academics</label>
	</div>
	
	<div id= "rating-assistance">
		<label>Professor Assistance</label>
	</div>
	
	<div id= "rating-life">
		<label>Student Life</label>
	</div>
	
	<div id= "rating-campus">
		<label>Campus</label>
	</div>
	
	<div id= "rating-return">
		<label>Return on Investment</label>
	</div>
	
	<div id= "rating-delay">
		<label>Delay on Graduation (per semester)</label>
	</div>
	
	<div id= "rating-career">
		<label>Career Opportunity</label>
	</div>
	

	<%= f.input :comment %>
	<%= f.button :submit %>

<% end %>

<script>
	$('#rating-campus').raty({
		
		path: '/assets/',
		scoreName: 'review[campus]'
	});
</script>
<script>
	$('#rating-return').raty({
		
		path: '/assets/',
		scoreName: 'review[return]'
	});
</script>
<script>
	$('#rating-delay').raty({
		
		path: '/assets/',
		scoreName: 'review[delay]'
	});
</script>
<script>
	$('#rating-career').raty({
		
		path: '/assets/',
		scoreName: 'review[career]'
	});
</script>

<script>
	$('#rating-form').raty({
		
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>
<script>
	$('#rating-academics').raty({
		
		path: '/assets/',
		scoreName: 'review[academics]'
	});
</script>
<script>
	$('#rating-assistance').raty({
		
		path: '/assets/',
		scoreName: 'review[assistance]'
	});
</script>

<script>
	$('#rating-life').raty({
		
		path: '/assets/',
		scoreName: 'review[life]'
	});
</script>

app/views/reviews/_review.html.erb
<div class = "row">
		<div class = "col three">	

			<p><label>Overall quality</label><span class="btn btn-custom3"><%= review.rating %></span></p>
			<p><label>Academics</label><span class="btn btn-custom3"><%= review.academics %></span></p>
			<p><label>Assistance</label><span class="btn btn-custom3"><%= review.assistance %></span></p>
			<p><label>Return on Investment</label><span class="btn btn-custom3"><%= review.return %></span></p>

		</div>

		<div class = "col three">

			<p><label>Social</label><span class="btn btn-custom3"><%= review.life %></span></p>
			<p><label>Campus</label><span class="btn btn-custom3"><%= review.campus%></span></p>
			<p><label>Delay Graduation </label><span class="btn btn-custom3"><%= review.delay %></span></p>
			<p><label>Career</label><span class="btn btn-custom3"><%= review.career%></span></p>

			
		</div>

		<div class = "col six">
			<p class ="comment_text"><label>Comment: </label><%= review.comment %></p>

			<% if user_signed_in? %>
				<% if review.user_id == current_user.id %>

					<div class = "links btn-group">
						<%= link_to "Edit", edit_school_review_path(review.school, review ), class:"btn btn-custom" %>
						<%= link_to "Delete", school_review_path(review.school, review), method: :delete, data:  {confirm: "Are you sure?"}, class:"btn btn-custom" %>
					</div>
				<% end %>
			<% end %>
		</div>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>


<%= simple_form_for ([@school, @review]) do |f| %>

	<div id= "rating-form">
		<label>Quality</label>
	</div>

	<div id= "rating-academics">
		<label>Academics</label>
	</div>
	
	<div id= "rating-assistance">
		<label>Professor Assistance</label>
	</div>
	
	<div id= "rating-life">
		<label>Student Life</label>
	</div>
	
	<div id= "rating-campus">
		<label>Campus</label>
	</div>
	
	<div id= "rating-return">
		<label>Return on Investment</label>
	</div>
	
	<div id= "rating-delay">
		<label>Delay on Graduation (per semester)</label>
	</div>
	
	<div id= "rating-career">
		<label>Career Opportunity</label>
	</div>
	
	<%= f.input :comment %>
	<%= f.button :submit %>
<% end %>

<script>
	$('#rating-campus').raty({
		
		path: '/assets/',
		scoreName: 'review[campus]'
	});
</script>
<script>
	$('#rating-return').raty({
		
		path: '/assets/',
		scoreName: 'review[return]'
	});
</script>
<script>
	$('#rating-delay').raty({
		
		path: '/assets/',
		scoreName: 'review[delay]'
	});
</script>
<script>
	$('#rating-career').raty({
		
		path: '/assets/',
		scoreName: 'review[career]'
	});
</script>

<script>
	$('#rating-form').raty({
		
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>
<script>
	$('#rating-academics').raty({
		
		path: '/assets/',
		scoreName: 'review[academics]'
	});
</script>
<script>
	$('#rating-assistance').raty({
		
		path: '/assets/',
		scoreName: 'review[assistance]'
	});
</script>

<script>
	$('#rating-life').raty({
		
		path: '/assets/',
		scoreName: 'review[life]'
	});
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= render 'form' %>

app/views/schools/_form.html.erb
<%= simple_form_for @school do |f| %>
	<%= f.input :title, label: "School Name" %>
	<%= f.input :location %>
	<%= f.input :program %>
	<%= f.button :submit %>
<% end %>

app/views/schools/edit.html.erb
<h1>Edit School</h1>
<%=  render 'form' %>

app/views/schools/index.html.erb
<h3 class = "header" >International Student School Review</h3>
<div class = "row">
	<% @schools.each do |school| %>
		<div class = "col-md-12">
			<div class = "struct">
				<h3><%= link_to school.title, school_path(school)  %></h3>
				<p style = "text-indent: 30px">Location: <%= school.location %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

app/views/schools/search.html.erb
<div class = "row">
	<% @schools.each do |school| %>
		<div class = "col-md-12">
			<div class = "struct">
				<h2><%= link_to school.title, school_path(school)  %></h2>
				<p style = "text-indent: 30px">Location: <%= school.location %></p>
			</div>
		</div>
	<% end %>
</div>

app/views/schools/show.html.erb
	<h2 class ="center"><%= @school.title %></h2>
	<h5 class ="center"><em>Based on <%= @school.reviews.count %> reviews </em></h5>

	<div class = "row">

		<div class = "col six">
			<div><label>Overall quality</label><span class ="average" data-score = <%=@average_rating%>></span></div>
			<div><label>Academics</label><span class ="average" data-score = <%=@average_academics%>></span></div>
			<div><label>Assistance</label><span class ="average" data-score = <%=@average_assistance%>></span></div>
			<div><label>Return on Investment</label><span class ="average" data-score = <%=@average_return%>></span></div>
		</div>

		<div class = "col six">
			<div><label>Student Life</label><span class ="average" data-score = <%=@average_life%>></span></div>
			<div><label>Campus</label><span class ="average" data-score = <%=@average_campus%>></span></div>
			<div><label>Delay Graduation (per semester)</label><span class ="average" data-score = <%=@average_delay%>></span></div>
			<div><label>Career After Graduation</label><span class ="average" data-score = <%=@average_career%>></span></div>
		</div>

	</div>


<h2 class = "center">Reviews <em>(out of 5)</em> </h2>

<div class = "center">
	<% if user_signed_in? %>
		<%= link_to "Add Review", new_school_review_path(@school), class: "btn btn-custom" %>
	<% else %>
		<%= link_to "Add Review", new_user_session_path, class: "btn btn-custom"%>
	<% end %>	
</div>

<%= render @school.reviews %>


<div class = "links btn-group">

	<%= link_to "Back", root_path, class: "btn btn-custom" %>
	
	<% if user_signed_in? %>
		<% if @school.user_id == current_user.id %>
			<%= link_to "Edit", edit_school_path(@school), class: "btn btn-custom"%>
			<%= link_to "Delete", school_path(@school), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-custom" %>
		<% end %>
	<% end %>

</div>



<script>
	$('.average').raty({
		readOnly: true,
		path: '/assets/',
		score: function() {
			return $(this).attr('data-score');
		},
		
	});
</script>